# Generated by Django 4.2.4 on 2023-08-17 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='tb_cliente',
        ),
    ]
