# Generated by Django 4.2.4 on 2023-08-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_veiculo_cor_veiculo_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoConcluida',
            fields=[
                ('numero_ordem', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('data_conclusao', models.DateField()),
                ('servico', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_conclusao_ordem', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.veiculo')),
            ],
            options={
                'db_table': 'tb_os_concluida',
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoAberta',
            fields=[
                ('numero_ordem', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('data_ordem', models.DateField()),
                ('servico', models.CharField(max_length=100)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.veiculo')),
            ],
            options={
                'db_table': 'tb_os_aberta',
            },
        ),
    ]
