# Generated by Django 4.2.4 on 2023-08-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_ordemservicoconcluida_ordemservicoaberta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoNaoAprovado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicos_propostos', models.TextField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_proposta', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.veiculo')),
            ],
            options={
                'db_table': 'tb_orcamentos_nao_aprovados',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoAprovado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicos_propostos', models.TextField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_aprovacao', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.veiculo')),
            ],
            options={
                'db_table': 'tb_orcamentos_aprovados',
            },
        ),
    ]
