# Generated by Django 4.2.4 on 2023-08-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_orcamentoaprovado_numero_orcamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentonaoaprovado',
            name='numero_orcamento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
