# Generated by Django 4.2.4 on 2023-08-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_orcamentonaoaprovado_numero_orcamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrcamentoAprovado',
        ),
    ]
