# Generated by Django 4.2.4 on 2023-08-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_delete_orcamentoaprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentonaoaprovado',
            name='cpf',
            field=models.CharField(default='desconhecida', max_length=14),
        ),
        migrations.AddField(
            model_name='orcamentonaoaprovado',
            name='email',
            field=models.EmailField(default='desconhecida', max_length=254),
        ),
        migrations.AddField(
            model_name='orcamentonaoaprovado',
            name='endereco',
            field=models.CharField(default='desconhecida', max_length=255),
        ),
        migrations.AddField(
            model_name='orcamentonaoaprovado',
            name='telefone',
            field=models.CharField(default='desconhecida', max_length=15),
        ),
    ]
