# Generated by Django 4.2.4 on 2023-08-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_orcamentonaoaprovado_cpf_orcamentonaoaprovado_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentonaoaprovado',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='orcamentonaoaprovado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orcamentonaoaprovado',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='orcamentonaoaprovado',
            name='telefone',
        ),
    ]
