# Generated by Django 4.2.4 on 2023-08-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_remove_orcamentonaoaprovado_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservicoconcluida',
            old_name='data_conclusao',
            new_name='data_inicio',
        ),
    ]
